### ISSUE TITLE
TO-263 pin numbering

### ISSUE THREAD

**Issue by jluebbe** [KiCad/SMD_Packages.pretty#17]
According to the JEDEC document (https://www.jedec.org/standards-documents/docs/263f), the bottom (thermal) pad has the highest pin number. For example TO-263.kicad_mod is described as variation AA and has pins 1-4 (4 being the bottom pad).

Can I simply fix the footprint and send a pull request or is there a reason for the different numbering?

**Comment by hackscribble** [comment]
Closing historic issue.
