### ISSUE TITLE
SSOP-28 missing

### ISSUE THREAD

**Issue by onitake** [KiCad/SMD_Packages.pretty#34]
A footprint for SSOP-28 seems to be missing.
Package dimensions can be found [here](http://cds.linear.com/docs/en/packaging/SSOP_28_05-08-1640.pdf), and a 3D model is already included within kicad-libs. It's called `SMD_Packages.3dshapes/SSOP-28.wrl`.

Please add the package.

**Comment by onitake** [comment]
Here's a footprint I created for myself, based on SSOP-20: https://gist.github.com/onitake/4e5997378b92d86f7e3f

The scaling should be more or less ok now.

**Comment by ricardocrudo** [comment]
hello @onitake, SSOP packages are here: KiCad/Housings_SSOP.pretty
