### ISSUE TITLE
new Housing_LLC.pretty

### ISSUE THREAD

**Issue by jkriege2** [KiCad/SMD_Packages.pretty#39]
Hi @SchrodingersGat ,
to go on moving footprints from this, could you also make a repo `Housings_LLC.pretty` for all the PLCC footrpints and other Lead-Chip-Carrier packages 8https://en.wikipedia.org/wiki/Chip_carrier#Plastic_leaded_chip_carrier)

best,
JAN

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/Housings_LLC
